version: '3'

services:
  db:
    image: mysql:8.0.31
    container_name: mysql-db
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=storefront
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin_admin
    volumes:
      - "./db/:/var/lib/mysql"

